# Generated by Django 3.2.12 on 2022-11-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_urun_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='urun',
            name='aciklama',
            field=models.TextField(max_length=500, verbose_name='Ürün açıklaması'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Ürün ismi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='no',
            field=models.IntegerField(verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='urunler/', verbose_name='Ürün resmi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategori'),
        ),
    ]
