# Generated by Django 4.1.3 on 2023-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('urunler', '0010_sepet_odendimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='kullanicilar',
            field=models.ManyToManyField(to='user.profile'),
        ),
    ]
